### ISSUE TITLE
ETL script to copy all approved legacy captures into treetracker schema

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-api#46]
All records in public.trees with active=true and approved=true are approved captures.  Create a script that copies all of these into treetracker.capture table.   If a treetracker.capture.uuid already exists, simply continue to the next record (this allows the script to be rerun to migrate new legacy data). 

Other requirements for production readiness of this script.
The associated treetracker.grower_account will also need to be created or linked based on the associated public.planter record (foreign key public.trees.planter_id).

**Comment by ZavenArra** [comment]
@arunbakt Here is some SQL that I created to populate test data, which could be a starting point.

```
INSERT INTO treetracker.capture
(
reference_id,
image_url,
lat,
lon,
gps_accuracy,
estimated_geometric_location,
grower_id,
grower_photo_url,
grower_username,
planting_organization_id,
device_configuration_id,
session_id,
created_at,
updated_at,
estimated_geographic_location,
status)
SELECT
id,
image_url,
lat,
lon,
gps_accuracy,
estimated_geometric_location,
'85fff895-33c8-4d89-a9b9-60b722beab60',
planter_photo_url,
'-',
uuid_generate_v4(),
uuid_generate_v4(),
uuid_generate_v4(),
time_created,
now(),
ST_SetSRID( ST_Point( lon, lat), 4326)::geography,
'active'
FROM trees
WHERE active = true
AND approved = true
AND image_url IS NOT NULL;
```

**Comment by arunbakt** [comment]
@ZavenArra When I populate `treetracker.grower_account`, it mandates presence of `wallet` and `wallet_id`. Where would I get it from? Should I use `token_id` in `public.trees` and retrieve it from `wallet.tokens` ? Also, is `token_id` gaurenteed to be in `public.trees`?

**Comment by ZavenArra** [comment]
PR is in domain migration scripts

**Comment by dadiorchen** [comment]
@arunbakt have you finished this?

**Comment by arunbakt** [comment]
@dadiorchen , PR is here https://github.com/Greenstand/domain-migration-scripts/pull/4. Testsed in dev db. PR has the test results when running in dev db.

**Comment by Kpoke** [comment]
@dadiorchen @gwynndp @sebastiangaertner @ZavenArra I think the best case here might be to do the migration for both the field-data (pre bulk pack version 2) and the treetracker schemas at the same time. Due to 

1. captures in the treetracker schema and raw-captures in the field-data are to have the same id(uuid), creating first for the treetracker schema before the field-data would affect that.
2. There are some fields in the treetracker captures table whose values are to come from the field_data (session_id and device_configuration_id)
3. Based on the implementation of the bulk pack v2 to support v1 bulk pack, we already have a template for how we could migrate data from the legacy database to the field data, and once we do that for field_data then creating the treetracker equivalent would be straightforward

**Comment by gwynndp** [comment]
@Kpoke 

Although I made the assumption that the raw-captures and captures would share a uuid, Nick pointed out that undermined the purpose of the ids being "universally unique".  Instead we want to use the reference_id as a consistent identifier between schemas and with the legacy api.

Regarding data migration, what do you think of doing an initial round with the new microservices by moving the legacy capture data only into the field-data/raw_captures,  then we can go through the process of verifying a few and confirming they are being approved/rejected/tagged properly and identified as trees in Capture Match?

**Comment by Kpoke** [comment]
https://github.com/Greenstand/domain-migration-scripts
